# ReLU activation function

In [ ]:
import numpy as np

In [ ]:
# relu activation function
inputs = [ 0 , 2 , - 1 , 3.3 , - 2.7 , 1.1 , 2.2 , - 100 ]
output = np.maximum(0,inputs)
print (output)

In [ ]:
from nnfs.datasets import spiral_data
import nnfs
nnfs.init()

In [ ]:
import matplotlib.pyplot as plt
X, y = spiral_data(samples=100, classes=3)


In [ ]:
class Layer_Dense:
    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        #initialize weights and biases
        
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        print("sdjfksd", np.random.randn(n_inputs, n_neurons))
        self.biases = np.zeros((1, n_neurons))
    
    #Forward pass
    def forward(self, inputs):
        # calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases

In [ ]:
# ReLU activation
class Activation_ReLU :
    
    # Forward pass
    
    def forward ( self , inputs ):
        
        # Calculate output values from input
    
        self.output = np.maximum( 0 , inputs)

In [ ]:
# Create dataset
X, y = spiral_data( samples = 100 , classes = 3 )
print(X)
print(y)
# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense( 2 , 3 )
# Create ReLU activation (to be used with Dense layer):
activation1 = Activation_ReLU()
# Make a forward pass of our training data through this layer
dense1.forward(X)

# Forward pass through activation func.
# Takes in output from previous layer
activation1.forward(dense1.output)

# Let's see output of the first few samples:
print (activation1.output[: 5 ])

## Softmax Activation function


In [ ]:
#values from the previous output when we described what a neural network was

layer_outputs = [4.8, 1.21, 2.385]

e = 2.71828182846

# For each value within the vector, calculate the exponential value
exp_values = []
for output in layer_outputs:
   exp_values.append(e**output)
print (exp_values)

- We now normalize the values

In [ ]:
# We now normalize the values
norm_base = sum(exp_values) # sum each value

norm_values = []
for value in exp_values:
    norm_values.append(value/norm_base)
print(norm_values)   

print('sum of normalized values', sum(norm_values))

In [ ]:
import numpy as np
# values from the earlier previous when we described what a NN was

layer_outputs = [4.8, 1.21, 2.385]

# For every value in a vector > calculate its exponated value

exp_values = np.exp(layer_outputs)

print(exp_values)

norm_values = exp_values / np.sum(exp_values)

print(norm_values)
print('sum of normalized values', np.sum(norm_values))

In [ ]:
layer_outputs = np.array([[4.8, 1.21, 2.385],
                         [8.9, -1.81, 0.2],
                          [1.41, 1.051, 0.026]])

print('sum axis 1, but keep the dimensions as input: ')
print(np.sum(layer_outputs, axis = 1, keepdims = True))

In [ ]:
class Activation_Softmax:
    # Forward pass
    def forward(self, inputs):
    
        # Get unnormalized probabilties
        exp_values = np.exp(inputs-np.max(inputs, axis = 1, keepdims=True))
  

        # Normalize them for each sample
        
        probabilties = exp_values/np.sum(exp_values, axis = 1, keepdims = True)

        self.output = probabilties

In [ ]:
softmax = Activation_Softmax()

softmax.forward([[1,2,3]])
print(softmax.output)
softmax.forward([[ - 2 , - 1 , 0 ]]) # same idea as the values are just 0 negated
print(softmax.output)

In [ ]:
softmax.forward([[0.5, 1, 1.5]])
print(softmax.output)

In [ ]:
# Create dataset
X, y = spiral_data( samples = 100 , classes = 3 )

# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense( 2 , 3 )

# Create ReLU activation (to be used with Dense layer):
activation1 = Activation_ReLU()

# Create second Dense layer with 3 input features (as we take output
# of previous layer here) and 3 output values
dense2 = Layer_Dense( 3 , 3 )

# Create Softmax activation (to be used with Dense layer):
activation2 = Activation_Softmax()

# Make a forward pass of our training data through this layer
dense1.forward(X)

# Make a forward pass through activation function
# it takes the output of first dense layer here
activation1.forward(dense1.output)

# Make a forward pass through second Dense layer
# it takes outputs of activation function of first layer as inputs
dense2.forward(activation1.output)

# Make a forward pass through activation function
# it takes the output of second dense layer here
activation2.forward(dense2.output)
# Let's see output of the first few samples:
print (activation2.output[: 5 ])

In [103]:

# run for a complete overview

import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # init the weights and biases
        
        # set the weights
        # https://www.mathsisfun.com/data/standard-normal-distribution.html, default mean = 0 and variance =1 
        # this just creates a random from -3 to 3 , but multiplies it by 0.01 to gain a faster time to calculate
        # NN prefer data between 1 and -1
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
 
        # create an array of shape (1, n_neurons) filled with zeros
        self.biases = np.zeros(( 1 , n_neurons))
     
    def forward(self, inputs):
        # forward pass performs the dot added to the biases of course

        self.output = np.dot(inputs, self.weights) + self.biases
        

# activations for the dense layer 
class Activation_ReLU:
    
    #forward pass
    def forward(self, inputs):
        #calculate output values from inputs, relu just takes max of 0 and the input whatever is larger
        self.output = np.maximum(0, inputs)
        
        
# use exponential as its always positive and exagerrates the difference of inputs more as its a power        
class Activation_Softmax:
    #forward pass
    
    def forward(self, inputs):
        
        # get unnormalized probabilities
        
        # takes e^(inputs - largest value from inputs)
        
        # take the max value to become 0 , so its output is always 1 to indicate the highest 
        # prevent dead neurons and large exploding numbers
        # if this was not done, then one value could be massive and make the sum

        print(inputs)
        exp_values = np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))
        print(exp_values)
       
        # normalize them for each sample, takes all values and divides by the sum 
        probabilties = exp_values / np.sum(exp_values, axis = 1, keepdims = True)
      
        self.output = probabilties
 
# returns 2 coordinates as features that represent each of classes
# repeats this for how many times the samples go down.
# attemps to consruct the original graph and colour based on when we get to where we assign labels to it if supervised.
X, y = spiral_data(samples = 4, classes = 2)

print("y: ", y)
print("X: ", X)

# 2 input features and 3 output values
dense1 = Layer_Dense(2,3)

# create relu activation to be used in dense layer

activation1 = Activation_ReLU()

# Create second Dense layer with 3 input features (as we take output
# of previous layer here) and 3 output values (output values)
dense2 = Layer_Dense( 3 , 3 )

# Create Softmax activation (to be used with Dense layer):
activation2 = Activation_Softmax()

# Make a forward pass of our training data through this layer
dense1.forward(X)

# Make a forward pass through activation function
# it takes the output of first dense layer here
activation1.forward(dense1.output)

# Make a forward pass through second Dense layer
# it takes outputs of activation function of first layer as inputs
dense2.forward(activation1.output)

# Make a forward pass through activation function
# it takes the output of second dense layer here
activation2.forward(dense2.output)

# the largest one here is the class to select
print (activation2.output)

y:  [0 0 0 0 1 1 1 1]
X:  [[ 0.          0.        ]
 [-0.12729016 -0.30807194]
 [ 0.51077586  0.4284302 ]
 [-0.9922136   0.12454799]
 [-0.         -0.        ]
 [ 0.09158143  0.32050577]
 [-0.66041565 -0.09108007]
 [ 0.8794786   0.47593853]]
[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.7768796e-05  4.4020140e-05  5.0318155e-05]
 [ 1.2585385e-05  9.4610687e-06  4.2363412e-05]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 1.1695344e-06  2.7461916e-05  4.8694048e-05]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-3.5273497e-05  5.4776192e-05  4.4027292e-05]]
[[1.         1.         1.        ]
 [1.         1.         1.        ]
 [0.99993193 0.9999937  1.        ]
 [0.9999702  0.9999671  1.        ]
 [1.         1.         1.        ]
 [0.9999525  0.9999788  1.        ]
 [1.         1.         1.        ]
 [0.99990994 1.         0.9999893 ]]
[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.3333189